spring:
  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 6379

  jwt:
    accessSecret: yOeHjKegnwjbli5csZbO1jE9r+qoGkpWgX2JdHjw3tI=
    refreshSecret: gjX7hf+563vQH/SMDh+K+A3MAbICvd3MtPLk/sZwizw=

  datasource:
    url: jdbc:h2:tcp://localhost/~/gsmforum
    driver-class-name: org.h2.Driver
    username: asdf
    password: 12345678

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create-drop


