spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/gsmforum
    driver-class-name: org.h2.Driver
    username: asdf
    password: 12345678

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create-drop

